/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * The type of drink.
 */
export enum DrinkType {
    Cocktail = "cocktail",
    NonAlcoholic = "non-alcoholic",
    Beer = "beer",
    Wine = "wine",
    Spirit = "spirit",
    Other = "other",
}
